#!/bin/bash
clear
#"This script is created by Vikas (Vikas)"
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
NORMAL="\033[0;39m"
try="Yes"
target="None"
my_head()
{

echo -e $BIBlue"-------------------------------------------------------------------------------------------------------------------------------------------"
        echo -e " Automation Tool to automate day to day Unix Tasks!!\c"
        echo -e "\tTrial=$try \c"
        echo -e "\tTarget Servers : $target"
        echo -e "-------------------------------------------------------------------------------------------------------------------------------------------"$NORMAL
}
while true
do
        my_head
    echo -e $BIPurple"Please select your choice From below menu \n "
        echo -e " 1.  Pre-validation (To capture pre-change configurations details) \n "
        echo -e " 2.  User Administration \n "
        echo -e " 3.  Disk Alert \n "
        echo -e " 4.  Run Ad Hoc Commands \n "
        echo -e " 5.  Services \n "
        echo -e " 6.  Health Check Statistics \n" 
        echo -e " 22. Options  \n "
        echo -e " 0.  Exit      \n "$NORMAL
        echo -e " Enter your Choice : \c"
        read cho
        case $cho in

        0)
               clear
               break
               ;;
        1)    
                if [ $target  = "None" ] ; then
                        echo -e "Select Target Servers from Option 22"
                        read dummy
                else
                        if [ $try  = "Yes" ] ; then
                               cd /etc/ansible/demo/prevalidation
                               clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Pre-validation (To capture pre-change configurations details)#########" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                               cat pre_valid_scrtry.yml | sed "s/abcz/$target/g" > pre_valid_scrtry1.yml
                               ansible-playbook pre_valid_scrtry1.yml -K
                               sleep 15
                               clear
                else
                               clear
                               cd /etc/ansible/demo/prevalidation
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Pre-validation (To capture pre-change configurations details)#########" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL

                               cat pre_valid_scr.yml | sed "s/abcz/$target/g" > pre_valid_scr.yml1
                               ansible-playbook pre_valid_scr.yml1 -K
                               sleep 15
                               clear
                       fi
                fi
                ;;
  
        2)
                if [ $target  = "None" ] ; then
                        echo -e "Select Target Servers from Option 22"
                        read dummy
                else
                        if [ $try  = "Yes" -o $try = "No" ] ; then
                while true
                do
                       clear
                       echo -e " \n"
                       echo -e $BIPurple" 1. User Creation \n"
                                echo -e " 2. User Removal \n"
				echo -e " 3. Group Add \n"
                                echo -e " 4. Password Reset \n"
                                echo -e " 5. Add Entry in Sudoers file \n"
                                echo -e " 6. User's details like Last login, Group Name etc \n"
				echo -e " 0. Exit \n "$NORMAL
				echo -e " Enter your Choice : \c"
				read cho
				case $cho in

				0)
                                clear
     				break
    				 ;;
				1)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Usercreation Scripts for Unix Servers ################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                                cd /etc/ansible/demo/usercreation
                                cat usercr.yml | sed "s/abcz/$target/g" > usercr1.yml
                                ./scr2
                                sleep 10
                                ;;
                                3)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Group Add Scripts for Unix Servers ###################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                                cd /etc/ansible/demo/usercreation/groupadd
                                cat grpadd.yml | sed "s/abcz/$target/g" > grpadd2.yml
                                ./scr
                                ;;
                                4)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Password Reset Scripts for Unix Servers ##############################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                                cd /etc/ansible/demo/passwdreset
                                cat usercr.yml | sed "s/abcz/$target/g" > usercr1.yml
                                ./scr
                                ;;
                                5)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Add Entry in Sudoers for Unix Servers ################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                                cd /etc/ansible/demo/sudoers
                                cat sudoers.yml | sed "s/abcz/$target/g" > sudoer.yml
                                ./scr1
                                ;;
                                2)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"User Removal for Unix Servers ########################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                                cd /etc/ansible/demo/usercreation/userdel
                                cat usercr.yml | sed "s/abcz/$target/g" > usercr_new.yml
                                ./scr1
                                ;;
                                6)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"User's details like Last login, Group Name etc########################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                                cd /etc/ansible/demo/usercreation/userdetails
                                cat copy_run_scr.yml | sed "s/abcz/$target/g" > copy_run.yml
                                ./scr1
                                sleep 7
                                ;;
                                *)
                                echo -e "Wrong Choice !!!!"
                                read dummy
                                continue
                                ;;
                                esac
                        done  
                        fi
                fi
                ;;
        3)
                if [ $target  = "None" ] ; then
                        echo -e "Select Target Servers from Option 22"
                        read dummy
                else
                        if [ $try  = "Yes" -o $try  = "No" ] ; then
                        cd /etc/ansible/demo/disk_alert
                        cat disk_alert.yml | sed "s/abcz/$target/g" > disk_alert1.yml
                        ansible-playbook disk_alert1.yml -K
                        fi
                fi
                ;;
        4)
                if [ $target  = "None" ] ; then
                        echo -e "Select Target Servers from Option 22"
                        read dummy
                else
                        if [ $try  = "Yes" ] ; then
                                cd /etc/ansible/demo/copyrunscrpt
                                cat copy_run_scr.yml | sed "s/abcz/$target/g" > copy_run_scr_new.yml
                                cat copy_run_norm_scr.yml  | sed "s/abcz/$target/g" > copy_run_norm_scr_new.yml
                                ./scr3
                        else
                                cd /etc/ansible/demo/copyrunscrpt
                                cat copy_run_scr.yml | sed "s/abcz/$target/g" > copy_run_scr_new.yml
                                cat copy_run_norm_scr.yml  | sed "s/abcz/$target/g" > copy_run_norm_scr_new.yml
                                ./scr2
                        fi
                fi
                ;;
        5)
              if [ $target  = "None" ] ; then
                    echo -e "Select Target Servers from Option 22"
                    read dummy
               else
                   if [ $try  = "Yes" -o $try  = "No"  ] ; then
               while true
               do
             echo -e $BIPurple" 1. Service Start \n "
                      echo -e " 2. Serice Stop \n "
                      echo -e " 3. Service Enabled \n "
                      echo -e " 4. Service Disabled \n "
                      echo -e " 0. Exit \n "$NORMAL
                      echo -e " Enter your Choice : \c"
                      read cho
                      case $cho in
                    
                      0)
                              clear
                              break
                              ;;
                      1)
             echo -e $BIPurple" a. FTP Start \n "
                      echo -e " b. NFS Start \n "
                      echo -e " c. HTTPD Start \n "
                      echo -e " 0. Exit \n"$NORMAL
                      echo -e " Enter your Choice : \c"
                      read cho
                      case $cho in
                   
                      0)
                              clear
                              break
                              ;;
                      a)
                      ansible $target -m service -a "name=vsftpd state=started" --become -K
                              ;;
                      b)
                      ansible $target m service -a "name=nfs state=started" --become -K
                      ;; 
                      c)
                      ansible $target -m service -a "name=httpd state=started" --become -K
                      ;;
                      *)
                      echo -e "Wrong Choice !!!!"
                      read dummy
                      continue
                      ;;
                      esac
                      ;; 
                      2)
             echo -e $BIPurple" a. FTP Stop \n "
                      echo -e " b. NFS Stop \n "
                      echo -e " c. HTTPD Stop \n "
                      echo -e " 0. Exit \n"$NORMAL
                      echo -e " Enter your Choice : \c"
                      read cho
                      case $cho in
        
                      0)
                           clear
                           break
                           ;;
                      a)
                      ansible $target -m service -a "name=vsftpd state=stopped" --become -K
                      ;;
                      b)
                      ansible $target -m service -a "name=nfs state=stopped" --become -K
                      ;;
                      c)
                      ansible $target -m service -a "name=httpd state=stopped" --become -K
                      ;;
                      *)
                      echo -e "Wrong Choice !!!!"
                      read dummy
                      continue
                      ;;
                      esac
                      ;;
                      3)
             echo -e $BIPurple" a. Enabled FTP Service \n "
                      echo -e " b. Enabled NFS Service \n "
                      echo -e " c. Enabled HTTPD Service \n "
                      echo -e " 0. Exit \n"$NORMAL
                      echo -e " Enter your Choice : \c"
                      read cho
                      case $cho in
                 
                      0)
                           clear
                            break
                            ;;
                      a)
                      ansible $target -m service -a "name=vsftpd enabled=yes" --become -K
                      ;;
                      b)
                      ansible $target -m service -a "name=nfs enabled=yes" --become -K
                      ;;
                      c)
                      ansible $target -m service -a "name=httpd enabled=yes" --become -K
                      ;;
                      *)
                      echo -e "Wrong Choice !!!!"
                      read dummy
                      continue
                      ;;
                      esac
                      ;;
                      4)
             echo -e $BIPurple" a. Disabled FTP Service \n "
                      echo -e " b. Disabled NFS Service \n "
                      echo -e " c. Disabled HTTPD Service \n "
                      echo -e " 0. Exit \n"$NORMAL
                      echo -e " Enter your Choice : \c"
                      read cho
                      case $cho in
                 
                      0)
                            clear
                            break
                            ;;
                      a)
                      ansible $target -m service -a "name=vsftpd enabled=no" --become -K
                      ;;
                      b)
                      ansible $target -m service -a "name=nfs enabled=no" --become -K
                      ;;
                      c)
                      ansible $target -m service -a "name=httpd enabled=no" --become -K
                      ;;
                      *)
                      echo -e "Wrong Choice !!!!"
                      ready dummy
                      continue
                      ;;
                      esac
                      ;;
                      *)
                      echo -e "Wrong Choice !!!!"
                      read dummy
                      continue
                     ;;

              esac
              done
  fi
 fi
               ;;
        6) 
               if [ $target  = "None" ] ; then
                       echo -e "Select Target Servers from Option 22"
                       read dummy
                else
                    if [ $try  = "Yes" -o $try  = "No" ] ; then
                    clear
                while true
                do
                       echo -e "    "
                       echo -e $BIPurple" 1. Memory Utilization \n "
                                echo -e " 2. CPU Utilization \n "
                                echo -e " 3. Overall I/O Activities \n"
                                echo -e " 4. Reports run queue and load average \n"
                                echo -e " 5. Report network statistics \n"
                                echo -e " 6. Top CPU Consuming Process \n"
                                echo -e " 7. Top Memory Consuming Process \n"
                                echo -e " 8. Shared Memory Statistic \n"
                                echo -e " 9. Capturing performance Statistics \n"
                                echo -e " 10.Packets capturing using tcpdump \n"
                                echo -e " 0. Exit \n "$NORMAL
                                echo -e " Enter your Choice : \c"
                       read cho in
                       case $cho in
                      
                               0)
                                    clear
                                    break
                                     ;;
                               1)
                                clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Real Live Memory Utilization Report###################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                               echo "  "
                               ansible $target -m shell -a "sar -r 1 3"
                               echo "  "
echo -e "kbmemfree: This shows the amount of free memory"
echo -e "Kbmemused: Memory used"
echo -e "%memused:  Percentage of memory used"
echo -e "kbbuffers: Buffer memory used by the kernel"
echo -e "kbcached:  Cached memory used by the kernel"
echo -e "Most likely you’ll focus on 'kbmemfree' and 'kbmemused' for free and used memory. \n"
                              sleep 5
                              clear
                              ;;
                               2)
                               clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Real Live CPU Utilization Report #####################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                              echo -e "  "
                              ansible $target -m shell -a "sar -u 1 3"
                              echo -e "  "
echo -e "%user   :This shows the total time that the processor is spending on different process"
echo -e "%sys    :This shows the percentage of time spend by the processor for operating system tasks"
echo -e "%iowait :The name iowait itself suggests that its the time spend by processor waiting for devices(input and output)"
echo -e "%steal  :This column shows the amount to time spend by a CPU (which is virtualized), for resources from the physical CPU"
echo -e "%idle   :This suggests the idle time spend by the processor \n"
                              sleep 5
                              clear
                              ;;
                              3)
                              clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Overall I/O Activities Report ########################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                              echo " " 
                              ansible $target -m shell -a "sar -b 1 3"
                              ansible $target -m shell -a "sar -p -d 1 1"

echo -e "rd_sec/s: This shows you the total number of sectors on that device which is being read"
echo -e "wr_sec/s: If rd_sec/s is sectors being read per second then obviously wr_sec is sectors being written per second"
echo -e "avgrq-sz: This column shows the average"
echo -e "await   : This shows the total number of time that the processor waited for requests regarding IO"
echo -e "%util   : This column shows the usage of cpu in percentage when the request was generated"
echo -e "tps     : Transactions per second (this includes both read and write)"
echo -e "rtps    : Read transactions per second"
echo -e "wtps    : Write transactions per second"
echo -e "bread/s : Bytes read per second"
echo -e "bwrtn/s : Bytes written per second \n"
                               sleep 5
                               clear
                              ;;
                              4)
                              clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Run queue and Load average Report ####################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                             echo " "
                             ansible $target -m shell -a "sar -q 1 3"
echo -e "This reports the run queue size and load average of last 1 minute, 5 minutes, and 15 minutes. '1 3' reports for every 1 seconds a total of 3 times. \n"
                             sleep 5
                             clear
                             ;;
                             5)
                             clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Report network statistics ############################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            echo " "
                            ansible $target -m shell -a "sar -n DEV 1 1"
                            echo " "
echo -e "IFACE   :Stands for the nic card interface name"
echo -e "rxpck/s :This shows the total packets received per second"
echo -e "txpck/s :Transmitted packets per second"
echo -e "rxcmp/s :Compressed packets received"
echo -e "txcmp/s :Compressed packets transmitted"
echo -e "rxmcst/s:Packets multicasted per second \n"
                            echo " "
                            sleep 5
                            clear
                            ;;
                            6)
                            clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Top CPU Consuming Process ############################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            echo " "
                            ansible $target -m shell -a "ps -eo pid,user,ppid,cmd,%mem,%cpu --sort=-%cpu | head"
                            echo " "
                            sleep 5
                            clear
                            ;;
                            7)
                            clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Top Memory Consuming Process #########################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            echo " "
                            ansible $target -m shell -a "ps -eo rss,vsz,pid,cputime,cmd --width 100 --sort rss,vsz | tail --lines 10"
                            echo " "
                            sleep 5
                            clear
                            ;;
                            8)
                            clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Shared Memory Statistics #############################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            echo " "
                            ansible $target -m shell -a "ipcs -ma"
                            echo " "
                            sleep 5
                            clear
                            ;;
                            9)
                            while true
                            do
                                 clear
                                 echo "   "
                                 echo -e $BIPurple" 1. Start Capturing Performance Statistics \n"
                                          echo -e " 2. Stop Monitoring Server \n"
                                          echo -e " 0. Exit \n "$NORMAL
                                          echo -e " Enter your Choice : \c"
                                           read cho
                                           case $cho in
 
                                 0)
                                       clear
                                       break
                                         ;;
                                 1)
                                 clear
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Capturing Performance Statistics #####################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            cd /etc/ansible/demo/adhoc_health
                            ./scr
                            sleep 10
                            clear
                            ;;
                            2)
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"Disabling Performance Statistics #####################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            crontab -e
                            clear
                            ;;
                            *)
                            echo -e "Wrong Choice !!!!"
                            read dummy
                            continue
                            ;;
                            esac
                            done
                            ;;
                            10)
                            clear
                            cd /etc/ansible/demo/tcpdump
echo -e $BIYellow"######################################################################" $NORMAL
echo -e $BIGreen"tcpdump packets capturing ############################################" $NORMAL
echo -e $BIYellow"######################################################################" $NORMAL
                            echo "    "
                            ./scr
                            sleep 8
                            clear
                            ;;
                            *)
                            echo -e "Wrong Choice !!!!"
                            read dummy
                            continue
                            ;;
                            esac
                          done
         fi
fi
   ;; 

        22)
                while true
                do
                        clear
                        my_head
                        echo -e " 1.  Trial : $try "
                        echo -e " 2.  Target Servers \n "
                        echo -e " 0.  Exit      \n "
                        echo -e " Enter your Choice : \c"
                        read cho
                        case $cho in

                        0)
                                clear
                                break
                                ;;
                        1)
                                if [ $try  = "Yes" ] ; then
                                        try="No"
                                else
                                        try="Yes"
                                fi
                                ;;
                        2)
                                echo -e ----------------------------------------------------------------------------
                                echo -e "Available Env :  All -> for All Server in this Env or Host IP "
                                cat /etc/ansible/hosts  | grep "\[" | sed "s/\[/ /g"  |  sed "s/\]/ /g"
                                echo -e ----------------------------------------------------------------------------
                                echo -e " Enter your Choice : \c"
                                read target
                                ;;

                        *)
                                echo -e "Wrong Choice !!!!"
                                read dummy
                                continue
                                ;;
                        esac
                done
                ;;
        *)
               echo -e "Wrong Choice !!!!"
               read dummy
               continue
               ;;
        esac
done

